### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by hpk22** [Vishvajeet590/CowinPy-Andy#1]
Bruh why is it while downloading saying that it contains a trojan virus. I am trying to download in MIUI

**Comment by Vishvajeet590** [comment]
Hi,
are you downloading it in chrome  or MI browser

**Comment by hpk22** [comment]
Chrome

**Comment by hpk22** [comment]
![Screenshot_2021-06-04-17-46-05-763_com miui global packageinstaller](https://user-images.githubusercontent.com/83662790/120799800-d0762980-c55c-11eb-92d2-0efe40439752.jpg)

**Comment by Vishvajeet590** [comment]
I don't why it's showing that. You can use any third-party file scanner like [Kaspersky](https://opentip.kaspersky.com/) or any to scan. That will for sure discourge users from using it. Till then I am finding why it is showing that.

**Comment by Vishvajeet590** [comment]
Ok, I am sure It's a false positive. As MIUI uses Avast and it has a good history of giving false positives for APK. For surety, you clone this repo in Android studio and run it from there.
Keep me notified if possible.

**Comment by hpk22** [comment]
Ok yeah.. I just tried your app... it's great.. I had two suggestions.
1). Can you also automate OTP
2). Is there any functionality to refresh at that moment by clicking enter or ctrl+C likewise ?

**Comment by Vishvajeet590** [comment]
> Ok yeah.. I just tried your app... it's great.. I had two suggestions.
> 1). Can you also automate OTP
> 2). Is there any functionality to refresh at that moment by clicking enter or ctrl+C likewise ?

I am working on automation of otp and for saving json file as currently app crashes on saving json.
