### ISSUE TITLE
App doesn't run in background

### ISSUE THREAD

**Issue by RonakTotla** [Vishvajeet590/CowinPy-Andy#10]
I've taken care of the battery optimization setup and allowed to run the app in background through app settings but it seems like it isn't running in background.
This I tell because after every refresh instance, the syntax print shows details like pincode, etc with time stamp of the instance. But once you switch over from this app to any other function and then go back, it doesn't give you the same syntax.

**Comment by Vishvajeet590** [comment]
Because I was not able to find any way to run the python compiler on a different thread other than UI thread. Until I find something in the documentation please bear with it.

**Comment by RonakTotla** [comment]
Sorry, I did not test it thoroughly. Upon running it now, I noticed that it is running fine. My bad.
I closed the issue.

**Comment by Vishvajeet590** [comment]
@RonakTotla Thanks bro testing this project thoroughly. I am more motivated to fix issues now. ✌👌
