### ISSUE TITLE
Unable to save json

### ISSUE THREAD

**Issue by RandommGuy** [Vishvajeet590/CowinPy-Andy#11]
Tried both apks.

In beta apk, after otp is received, without reading it, coming back to first screen.

in regular apk, it says "error 30-Read only file system"
Only if we opt n for saving json file, it is running.

**Comment by Vishvajeet590** [comment]
> Tried both apks.
> 
> In beta apk, after otp is received, without reading it, coming back to first screen.
> 
> in regular apk, it says "error 30-Read only file system"
> Only if we opt n for saving json file, it is running.

Hi, @RandommGuy fixed it. Thanks for informing me.  Otp2Pc might not work, will fix it tommorw.👏
