### ISSUE TITLE
apk can't install

### ISSUE THREAD

**Issue by circuitmamu** [Vishvajeet590/CowinPy-Andy#2]
apk can't install

There was a problem parsing the package

**Comment by Vishvajeet590** [comment]
Can you provide more details or screenshot.

**Comment by circuitmamu** [comment]
APK size around 110 KB

![Screenshot_2021-06-05-16-31-27-52_846b44643ec609f507828878741e1f9a](https://user-images.githubusercontent.com/14886847/120889674-e991df80-c61b-11eb-8bff-ab7daf0bb7fd.jpg)
![Screenshot_2021-06-05-16-31-38-75](https://user-images.githubusercontent.com/14886847/120889676-ebf43980-c61b-11eb-8e72-d42fe6bef7a7.jpg)

**Comment by Vishvajeet590** [comment]
Download it again and try for once more.
