### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by hpk22** [Vishvajeet590/CowinPy-Andy#3]
Is auto OTP working?
I downloaded new APK but I had to manually enter OTP

**Comment by Vishvajeet590** [comment]
It's working I forgot to add ask explicitly for SMS permission. I am adding doing that within half an hour. Till then go to settings and give SMS permission by yourself.

If possible notify if it works or any other problem.

**Comment by Vishvajeet590** [comment]
Hi, took more than half an hour. Added explicit permission check now it works like charm.

If possible notify if it works or any other problem. Also, share this repo with others if you liked .
