### ISSUE TITLE
Read only file system 

### ISSUE THREAD

**Issue by saurabhsharmaj** [Vishvajeet590/CowinPy-Andy#5]
Getting this permission issue

![Screenshot_2021_0608_000329](https://user-images.githubusercontent.com/7188167/121071184-41cc0b80-c7ed-11eb-9d1e-1f765f5a5e8e.png)

**Comment by abhi24ca** [comment]
Btw for auto book u have to write "yes-please" and not just "yes"

**Comment by Vishvajeet590** [comment]
yes-please

**Comment by saurabhsharmaj** [comment]
Its same even after that. There should some permission option.

Regards,
Saurabh

**Comment by saurabhsharmaj** [comment]
please update the apk after update the
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

permission.

**Comment by Vishvajeet590** [comment]
Hi @saurabhsharmaj  writing on internal storage doesn't require any permission.

**Comment by saurabhsharmaj** [comment]
Vishal how can fix this issue, this app throwing that read only error

Hi @saurabhsharmaj  you can download and install beta version it supports saving json profiles.

**Comment by Vishvajeet590** [comment]
> Vishal how can fix this issue, this app throwing that read only error

Download beta apk.
