### ISSUE TITLE
Rate limit update by cowin

### ISSUE THREAD

**Issue by circuitmamu** [Vishvajeet590/CowinPy-Andy#7]
**New rate limit by COWIN.**

Seven-day Search: 100 queries in 5 minutes OR 20 queries per session
after that ur requests got blocked
CALENDAR_URL_DISTRICT = "https://cdn-api.co-vin.in/api/v2/appointment/sessions/calendarByDistrict?district_id={0}&date={1}"
CALENDAR_URL_PINCODE = "https://cdn-api.co-vin.in/api/v2/appointment/sessions/calendarByPin?pincode={0}&date={1}"

Single-day Search: 100 queries in 300 seconds (5 minutes)
FIND_URL_DISTRICT = "https://cdn-api.co-vin.in/api/v2/appointment/sessions/findByDistrict?district_id={0}&date={1}"
FIND_URL_PINCODE = "https://cdn-api.co-vin.in/api/v2/appointment/sessions/findByPin?pincode={0}&date={1}"

For best results without being rate-limited, 
1. use a lower frequency (8 seconds or higher), AND
2. search for a single day using `dd-mm-yyyy` AND

**Comment by Vishvajeet590** [comment]
Thanks how did you got this data
