### ISSUE TITLE
Answer format for auto-booking

### ISSUE THREAD

**Issue by RonakTotla** [Vishvajeet590/CowinPy-Andy#8]
What should be the answer format for going with "yes" option for auto-booking?
The suggested answer is "yes-please" or "no"
So if the user want to go with auto-booking feature, should he write "yes-please" or just "yes" would do. 
It's bit confusing for the user. 
Do check it out

**Comment by Vishvajeet590** [comment]
Correct answer format is yes-please.
Will change it to SURE  in next push.

**Comment by RonakTotla** [comment]
Cool

**Comment by Vishvajeet590** [comment]
Hi, bro please star this repository if you liked it.
